[package]
name = "data-parallelism"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
image = "0.24.1"
glob = "0.3.0"
error-chain = "0.12.4"
